### ISSUE TITLE
huh?

### ISSUE THREAD

**Issue by jonhalltm** [learn-co-curriculum/dsc-json-lab-v2-1#2]
phase 1, module 3, JSON lab, one of the first things I'm asked to do is extract values from a dictionary from a list from a dictionary from a dictionary.  For someone who hasn't done this, this looks impossible.  I can't even figure out how to access those values, something like...

data['meta']['view']['columns'].keys()?  

I don't know, I just know that every list command I use gets a dictionary error and every dictionary command I try to use gets a list error.

I feel like I should have been given much easier problems to work with before trying to figure out a dictionary/list/dictionary/dictionary thing.  Please re-do this with intermediate steps of learning to practice.

**Comment by bpurdy-ds** [comment]
Closed commit using [fc67170](https://github.com/learn-co-curriculum/dsc-json-lab-v2-1/commit/fc67170abb92a56ad4bfb802f6e82b64d1bf1a95).
